# Generated by Django 5.0.6 on 2024-06-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default-image.jpg', upload_to='productos/'),
        ),
    ]
