# Generated by Django 5.0.6 on 2024-06-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
