# Generated by Django 5.0.6 on 2024-06-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_remove_productopedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
